### ISSUE TITLE
Getting wrong values from the HX711

### ISSUE THREAD

**Issue by einsiedlerkrebs** [hiveeyes/arduino#19] opened 2017-05-07 12:19 UTC
I am getting insane values from the scale. 

I am not sure, if this issue is cause of wrong code, or if the sensor does not work.

**Comment by amotl** [comment] 2017-11-02 00:16
Dear @einsiedlerkrebs,

i believe we already found the root cause and mitigated this issue with your setup so we can close this?

With kind regards,
Andreas.

**Comment by amotl** [comment] 2020-03-18 14:04
We just created #26 to update the HX711 library included within this repository to its most recent version.

**Comment by amotl** [comment] 2020-05-25 23:35
This is a rather old issue and I believe things have been sorted out in the meanwhile. Please reopen when you are still having issues, @einsiedlerkrebs.

**Closed by amotl** 2020-05-25 23:35 UTC
